### PR TITLE
feat(ZNTA-2234): Correct the codecov URL

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-2234

zanata/zanata-pipeline-library#5

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/openprops/6)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Jenkinsfile, line 8 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGmpEzd7kFAi524g1:-KwDGmpEzd7kFAi524g2:bb7462z) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L8)):*
> ```Groovy
> public static final String PIPELINE_LIBRARY_BRANCH = 'ZNTA-2234-codecov'
> 
> @Library('github.com/zanata/zanata-pipeline-library@ZNTA-2234-codecov')
> ```

TODO

---

*[Jenkinsfile, line 28 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGold-hvDbktTjZ1z:-KwDGold-hvDbktTjZ2-:bjiu4di) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L28)):*
> ```Groovy
> @Field
> def reporting
> reporting = new Reporting(env, steps, 'https://github.com/zanata/openprops.git')
> ```

We should be able to eliminate these lines once the codecov method becomes static.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/openprops/6)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Jenkinsfile, line 8 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGmpEzd7kFAi524g1:-KwDxnqxvcH6qNC2ESP6:b-uo5haz) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L8)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

:lgtm: otherwise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/openprops/6)*

**Comment by definite** [comment]
-(Awaiting review) 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Jenkinsfile, line 8 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGmpEzd7kFAi524g1:-KwJGVdZ8p6Dx8qGbwiz:b-896fix) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L8)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

:lgtm: otherwise
</blockquote></details>

Done.

---

*[Jenkinsfile, line 28 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGold-hvDbktTjZ1z:-KwJG_TQd0UIm2Iv57bF:b-896fix) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L28)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should be able to eliminate these lines once the codecov method becomes static.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/openprops/6#-:-KwJGj87AbFPS5rSncXZ:b-o9bygt)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Jenkinsfile, line 8 at r2](https://reviewable.io:443/reviews/zanata/openprops/6#-KwDGmpEzd7kFAi524g1:-KwbhC8LDV9g1IkmIvDW:b-aiy07c) ([raw file](https://github.com/zanata/openprops/blob/ee771a0121c6b0064707a880b2386a7f2bc443b9/Jenkinsfile#L8)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It doesn't look done. It still says `ZNTA-2234-codecov` instead of `master` (or better still: `0.2`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/openprops/6)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/openprops/6#-:-KxMc75XQNRAjspcArHu:bnfp4nl)*

**Pull request merged**
